# This workflow should build the website with Hugo and deploy it on
# GitHub pages. Edit this file as you wish, otherwise just make sure 
# that this folder contains a workflow exists that it is executed 
# upon pushing the source to the default branch.

name: Build and deploy GitHub pages with Hugo

on: push

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'
        
      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
#         external_repository: github.com/cs-ej4104-2021/paivihj-project
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
